Неделя 2
ok-technopolis-2021/Kondraev_Dmitry pull request #1
Opened 2021-10-04 22:16 UTC by mariohuq

- [x] Структура HTML-страницы

2021-10-20 22:12 UTC, aqus requested changes

2021-10-20 22:12 UTC, aqus commented on index.html
> +    <nav></nav>
для чего тут nav и header?

2021-10-20 22:12 UTC, aqus commented on index.html
> +        <article>
по идее этот блок должен идти после блока, который в aside, потому что по макету он находится правее, ну конечно, если не было задумки потом использовать float'ы

2021-10-20 22:12 UTC, aqus commented on index.html
> +        <aside>
почему исопльзуется aside?
документацию по нему можно поглядеть тут https://html.spec.whatwg.org/multipage/sections.html#the-aside-element
В aside можно положить второстепенный контент, который немного касается темы.
Насчет acticle https://html.spec.whatwg.org/multipage/sections.html#the-article-element
Тоже как-будто не очень подходит, можно положить в section, должно подойти по смыслу: какая-то секция с заголовком

2021-10-27 15:31 UTC, mariohuq commented on index.html
> +    <nav></nav>
Не нужны(

2021-10-27 15:35 UTC, mariohuq commented on index.html
> +        <article>
Я дальше использую

```css
flex-direction: row-reverse;
```

2021-10-27 15:37 UTC, mariohuq commented on index.html
> +        <aside>
Я, похоже путаю смысл `section` и `article`. Спасибо за ссылки.

2021-11-02 21:28 UTC, aqus approved these changes
1 ДЗ - 10 баллов

2021-11-02 21:28 UTC, aqus commented on index.html
> +            <form action="./media/kondraev-dmitry-java-dev-cv.pdf" method="get">
спорный момент, конечно, можно в данном случае использовать обычную ссылку с атрибутом download

2021-11-03 21:19 UTC, merged