Homework_5
ok-technopolis-2021/Kondraev_Dmitry pull request #5
Opened 2021-11-15 20:35 UTC by mariohuq

2021-11-16 10:03 UTC, BusinessDuck requested changes
По какой-то причине font-awesome не работает у меня на github pages, вероятно шрифты не доехали, но это не точно.

2021-11-16 10:03 UTC, BusinessDuck commented on package.json
> +        "@fortawesome/fontawesome-free": "^5.15.4",
Думаю, что зависимость отдающая артефакты на клиент при сборке, вполне имеет право быть в `dependencies`

2021-11-16 10:03 UTC, BusinessDuck commented on src/common.blocks/skill/skill.js
> +        const define = (target, properties) => {
при рендеринге, каждый раз будет создаваться эта функция, ее можно унести в отдельный файл utils.js

контракт мне не очень нравится, потому что не все свойства элемента можно задать через прямой доступ к свойству, некоторые свойства меняются только через `el.setAttribute();`

`document.createTextNode` можно попробовать заменить на `el.innerText = this.name`;

если хочется как то унифицировать то можно попробовать сделать так:

```javascript
function define(nodeName, className, innerText, parentNode) {
 const el = document.createElement(nodeName);
 el.className = className;
 
 if (innerText) {
   el.innerText = innerText;
 }
 
 if (parentNode) {
  parentNode.appendChild(el);
 }

return el;
}
```

2021-11-16 10:03 UTC, BusinessDuck commented on src/common.blocks/skill/skill.js
> +        define(
`define(define(define`, так точно не должно быть, это выглядит не читаемо, скорее всего если исправить контракт define, то это уйдет

2021-11-16 10:03 UTC, BusinessDuck commented on src/common.blocks/skill/skill.js
> +        target.querySelector('.skill-button_remove').addEventListener('click', function (event) {
не нужно заново искать эту ноду, ты ее выше создавал, используй ссылку на  созданный узел

2021-11-16 10:03 UTC, BusinessDuck commented on src/common.blocks/skills-list/skills-list.js
> +    for (const skill of [
если положить в отдельную переменную, будет проще. Например гит, если вдруг конфликты будут в этой области, не сможет их решить в том виде в каком ты написал цикл.

2021-11-16 10:22 UTC, mariohuq commented on package.json
> +        "@fortawesome/fontawesome-free": "^5.15.4",
Но ведь тут сборка решает, что именно из этой зависимости забрать на клиент.

Я немного не понял, в чем разница между `dependencies` и `devDependencies`. `npm install` устанавливает и те, и другие.

2021-11-16 10:26 UTC, mariohuq commented
@BusinessDuck, со шрифтами проблема в том, что в той версии шрифта, которую я подключил, нет используемых глифов. Не знаю, как оно работало у меня на локальной машине(

2021-11-16 11:14 UTC, BusinessDuck commented on package.json
> +        "@fortawesome/fontawesome-free": "^5.15.4",
разница в том, что если зависимость будет присутствовать на клиенте, ее обычно ставят в `dependencies`, а весь инструментарий сборки всякие плагины и тулзы для кода в девелоперские

2021-11-16 11:20 UTC, BusinessDuck commented
Еще в рамках наброса, у тебя нету четкого разделения на модель и на UI, есть еще способ явно разделить визуальное представление элемента и его логику, подумай какой способ лучше и чем лучше, я возможно попрошу аргументировать преимущества выбранного решения, каким бы оно не было, вопрос скорее "холиварный", чем имещий однозначный ответ. Но в любом случае будь готов аргументировать свои архитектурные решения.

2021-12-09 11:13 UTC, mariohuq commented on package.json
> +        "@fortawesome/fontawesome-free": "^5.15.4",
см. d290e2b

2021-12-09 11:13 UTC, mariohuq commented on src/common.blocks/skill/skill.js
> +        const define = (target, properties) => {
см. f94f223

2021-12-09 11:15 UTC, mariohuq commented on src/common.blocks/skills-list/skills-list.js
> +    for (const skill of [
см. ce285ed

2021-12-09 19:16 UTC, mariohuq commented on src/common.blocks/skill/skill.js
> +        target.querySelector('.skill-button_remove').addEventListener('click', function (event) {
см. f94f223

2021-12-09 19:16 UTC, mariohuq commented on src/common.blocks/skill/skill.js
> +        define(
см. f94f223

2021-12-14 07:42 UTC, BusinessDuck approved these changes
Мне очень понравилась реализация. Понравился стиль и подход к деталям. Все используемые элементы обоснованы, хорошо сгруппировано все. Ты не только слушаешь, что я говорю, но и думаешь сам, это очень хорошо. Работают все горячие клавиши для добавления скилов, tab, enter, стрелки вниз вверх, все выглядит очень прилично. Это точно работа на максмальный балл.

2021-12-14 07:44 UTC, BusinessDuck commented on src/common.blocks/skill/skill.js
> +                    tagName: 'span',
интересная реализация утилитарного метода отрисовки. Просто FYI знай что еще можно вот таким орбразом делать рендеринг https://developer.mozilla.org/ru/docs/Web/HTML/Element/template

2021-12-14 07:51 UTC, BusinessDuck commented
Твой подход работает напрямую с данными и данные связаны сразу и с моделью, это допустимо и не плохо. Сейчас в основном применяется в разработке реактивный подход. Это когда состояние модели описано отдельно, а  UI изменяется в зависимости от изменения модели. То есть у тебя есть массив данных в нашем случае это скилы, в него добавляются или удаляются скилы, и в зависимости от вида манипуляции с моделью DOM реагирует на это и перестраивается, вот ниже пример как этого можно добиться. Однако будет ряд трудностей, во первых не понятно как грамотно перерисовывать содержимое, потому что может удалиться элемент в середине, и как-то нужно вычислить, какой это элемент и удалить его точечно, также элемент может добавиться в конец или в начало (не в нашем случае а в общем). Все эти перерисовки сложно управляемы. Эту задачу решают фреймоврки как раз.

В общем и целом, реактивных подход позволяет хранить данные модели отдельно, тем самым получая к ним доступ из любых мест приложения и делая его более гибким. Для отслеживания изменений в модели чаще всего используется паттерн Observer, ссылка и описание ниже.


Вот еще несколько примеров реализации от меня

```typescript
export class Skill {
    constructor(readonly name: string, readonly value: number) {}
}

export class SkillList {
    private list: Array<Skill>;

    constructor() {
        this.list = [];
    }

    add(skill: Skill) {
        this.list.push(skill);
    }

    remove(skill: Skill) {
        this.list.splice(this.list.indexOf(skill), 1);
    }
}

export class SkillView {
    constructor(private skill: Skill) {}

    render() {
        return this.HTML(`<div class="skill">${this.skill.name}<span>${this.skill.value}</span></div>`);
    }

    private HTML(str: string) {
        // @ts-ignore
        return repalceHtmlEntities(str);
    }
}

export class SkillListView {
    private list: Array<SkillView>;

    render() {
        return this.list.map(skill => skill.render()).join('');
    }
}

export class SkillListController {
    private skillList: SkillList;
    private skillListView: SkillListView;

    constructor(private target: Element) {...}

    addSkill(...) {
        // ...
        const skill = new Skill('123', 33);
        this.skillList.add(skill);
        this.target.innerHTML = this.skillListView.render();
    }
}

// index.ts

const target = document.querySelector('.target');
const skillController = new SkillListController(target);

// В идеале вообще использовать Observer Pattern

// index2.ts
const target = document.querySelector('.target');
const model = new SkillList();
const skillController = new SkillListController(target, model);

function addSkill() {
    model.push({ name: 'asdf', value: 33 });
}

function removeSkill(idx) {
    model.removeSkill(idx);
}

// И где-то внутри контроллера скилов
// Мы подписались на изменения модели, то есть при добавлении и удалении элемента вызовется коллбек. Паттерн 
 Observer можно посмотреть тут
https://monsterlessons.com/project/lessons/observer-pattern-v-javascript
this.model.subscribe((model => {});
```

2021-12-14 07:51 UTC, BusinessDuck commented
это также FYI

2021-12-14 09:05 UTC, mariohuq commented on src/common.blocks/skill/skill.js
> +                    tagName: 'span',
`<template>` прекрасно подойдет тут
([src/common.blocks/skills-list/skills-list.js#R17](https://github.com/ok-technopolis-2021/Kondraev_Dmitry/pull/5/files#diff-5dd480787411a443b98741dbc7738d677fb90a2b4e5c3a31e3c7eab8410cb7bdR17))
и тут
([src/common.blocks/skill/skill_form.js#R13](https://github.com/ok-technopolis-2021/Kondraev_Dmitry/pull/5/files#diff-a6520aba8d8fd529bfcc4a6e11d4c648f5e65ad987571b477a1799f024407d87R13)), но, допустим, здесь 
([src/common.blocks/skill/skill_form.js#R20-R22](https://github.com/ok-technopolis-2021/Kondraev_Dmitry/pull/5/files#diff-a6520aba8d8fd529bfcc4a6e11d4c648f5e65ad987571b477a1799f024407d87R20-R22]), где `render` используется для перерисовки только атрибута стиля, он вряд ли поможет. Несмотря на это, это отличный инструмент, заменяющий кучу кода декларативным описанием.

2021-12-14 10:16 UTC, BusinessDuck approved these changes
В целом все ок, используй почаще export из файлов. А также не нужно все запихивать в DOMContentLoaded,  можно просто стартовую точку туда вставить в index.js файле и она уже запустит все остальное. В  остальном все ок.

2021-12-18 13:46 UTC, BusinessDuck approved these changes
Что понравилось писал в ревью предыдущих но добавлю еще
1) Стили крутые, визуально приятно
2) Кода сильно меньше чем могло бы быть при подобном подходе с добавлением элементов в ручном режиме
3) Импорты экспорты
4) Формы и горячие клавиши

Итого 40/40
Что не понравилось
1) Отдельная страница со скилами, лучше бы ее вписать в стиль интерфейса

2021-12-23 13:01 UTC, merged